#! /bin/bash

if [[ $1 == "-h" || $1 == "--help" ]] ; then
    echo "Usage: run automatically by git rebase"
    echo ""
    echo "Executes our .git/hooks/ctags script after git rebase is run."
    echo ""
    echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
    echo "https://github.com/convissor/ubuntu_laptop_installation"
    echo ""
    echo "The components combining git and ctags are based on"
    echo "http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html"
    exit 1
fi

case "$1" in
    rebase) exec .git/hooks/post-merge ;;
esac
